# Generated by Django 4.2.15 on 2024-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
