# Generated by Django 4.2.15 on 2024-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contactmessage_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
