# Generated by Django 4.2.15 on 2024-10-02 07:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                default="https://res.cloudinary.com/dx21s72fa/image/upload/v1727851756/fdabrnoqg0gvslw6qahm.svg",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
