# Generated by Django 4.2.15 on 2024-10-02 07:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_testimonial_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
